spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/platform
    username: sa
    password:
    driver-class-name: org.h2.Driver
  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  logging.level:
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      multiline: true
      enable-logging: true