spring:
  datasource:
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql

server:
  port: 9999

  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true